describe('template spec', () => {
  it('passes', () => {
    cy.visit('www.automationexercise.com/');
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click();
    cy.get('[data-qa="login-email"]').clear().type('raden@gmail.com');
    cy.get('[data-qa="signup-name"]').clear().type('Raden123');
    cy.get('[data-qa="signup-email"]').clear().type('raden1@gmail.com');
    cy.get('#susbscribe_email').clear().type('raden1@gmail.com');
    cy.get('[data-qa="login-email"]').clear().type('raden@gmail.com');
    cy.get('[data-qa="signup-name"]').clear().type('Raden123');
    cy.get('#susbscribe_email').clear().type('raden1@gmail.com');
    cy.get('[data-qa="signup-button"]').click();
    cy.get('[data-qa="password"]').clear().type('12345');
    cy.get('form > :nth-child(6)').click();
    cy.get('[data-qa="days"]').select('4');
    cy.get('[data-qa="months"]').select('5');
    cy.get('[data-qa="years"]').select('2014');
    cy.get('#newsletter').check();
    cy.get('#optin').check();
    cy.get('[data-qa="first_name"]').clear().type('Raden');
    cy.get('[data-qa="last_name"]').clear().type('Raden');
    cy.get('#susbscribe_email').clear().type('raden@gmail.com');
    cy.get('[data-qa="company"]').clear().type('ASD');
    cy.get('[data-qa="address"]').clear().type('Tokyo');
    cy.get('[data-qa="address2"]').clear().type('Tokyo');
    cy.get('[data-qa="country"]').select('Singapore');
    cy.get('[data-qa="state"]').clear().type('Tokyo');
    cy.get('[data-qa="city"]').clear().type('Tokyo');
    cy.get('[data-qa="zipcode"]').clear().type('1235');
    cy.get('[data-qa="mobile_number"]').clear().type('2345678');
    cy.get('[data-qa="create-account"]').click();
    cy.get(':nth-child(5) > .btn').click();
    cy.get('.modal-footer > .btn').click();
    cy.get('.shop-menu > .nav > :nth-child(3) > a').click();
    cy.get('.col-sm-6 > .btn').click();
    cy.get('.container > :nth-child(7)').click();
    cy.get('.form-control').click();
    cy.get(':nth-child(7) > .btn').click();
    cy.get('[data-qa="cvc"]').clear().type('12');
    cy.get('[data-qa="expiry-month"]').clear().type('12');
    cy.get('[data-qa="expiry-year"]').clear().type('122121');
    cy.get('[data-qa="pay-button"]').click();
    cy.get('[data-qa="continue-button"]').click();
  });
});
