describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://www.automationexercise.com/');
    cy.get('.shop-menu > .nav > :nth-child(2) > a').click();
    cy.get(':nth-child(3) > .product-image-wrapper > .choose > .nav > li > a').click();
    cy.get('.modal-footer > .btn').click();
    cy.get('.shop-menu > .nav > :nth-child(3) > a').click();
    cy.get(':nth-child(4) > a').click();
    cy.get('[data-qa="signup-button"]').click();
    cy.get('[data-qa="password"]').clear().type('12345');
    cy.get('[data-qa="days"]').select('10');
    cy.get('[data-qa="months"]').select('3');
    cy.get('form > :nth-child(6)').click();
    cy.get('[data-qa="years"]').select('2003');
    cy.get('form > :nth-child(7)').click();
    cy.get('#optin').check();
    cy.get('#newsletter').check();
    cy.get('[data-qa="first_name"]').clear().type('Raden');
    cy.get('[data-qa="last_name"]').clear().type('Raden123');
    cy.get('#susbscribe_email').clear().type('raden@gmail.com');
    cy.get('[data-qa="company"]').clear().type('ASD');
    cy.get('form > :nth-child(14)').click();
    cy.get('[data-qa="address"]').clear().type('Tokyo');
    cy.get('[data-qa="address2"]').clear().type('Tokyo');
    cy.get('[data-qa="country"]').select('Singapore');
    cy.get('[data-qa="state"]').clear().type('Tokyo');
    cy.get('[data-qa="city"]').clear().type('Tokyo');
    cy.get('[data-qa="zipcode"]').clear().type('1235');
    cy.get('[data-qa="mobile_number"]').clear().type('2345678');
    cy.get('[data-qa="create-account"]').click();
    cy.get('[data-qa="continue-button"]').click();
    cy.get('.col-sm-6 > .btn').click();
    cy.get('.form-control').click();
    cy.get(':nth-child(7) > .btn').click();
    cy.get('[data-qa="card-number"]').click().clear().type('123');
    cy.get('[data-qa="cvc"]').clear().type('23');
    cy.get('[data-qa="expiry-month"]').clear().type('24');
    cy.get('[data-qa="expiry-year"]').clear().type('2222');
    cy.get('[data-qa="pay-button"]').click();
  });
});
